---
openapi: 3.0.1
info:
  title: ProjectsManagingSystem
  version: '1.0'
paths:
  "/Member":
    post:
      tags:
        - Member
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MemberDto"
          text/json:
            schema:
              "$ref": "#/components/schemas/MemberDto"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/MemberDto"
      responses:
        '200':
          description: Success
  "/Member/{id}":
    get:
      tags:
        - Member
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Member
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
    put:
      tags:
        - Member
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MemberDto"
          text/json:
            schema:
              "$ref": "#/components/schemas/MemberDto"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/MemberDto"
      responses:
        '200':
          description: Success
  "/Member/register":
    post:
      tags:
        - Member
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MemberDto"
          text/json:
            schema:
              "$ref": "#/components/schemas/MemberDto"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/MemberDto"
      responses:
        '200':
          description: Success
  "/Member/login":
    post:
      tags:
        - Member
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LoginDto"
          text/json:
            schema:
              "$ref": "#/components/schemas/LoginDto"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/LoginDto"
      responses:
        '200':
          description: Success
  "/Project":
    post:
      tags:
        - Project
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ProjectDto"
          text/json:
            schema:
              "$ref": "#/components/schemas/ProjectDto"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/ProjectDto"
      responses:
        '200':
          description: Success
  "/Project/{id}/task":
    post:
      tags:
        - Project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ProjectTaskDto"
          text/json:
            schema:
              "$ref": "#/components/schemas/ProjectTaskDto"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/ProjectTaskDto"
      responses:
        '200':
          description: Success
  "/Project/{id}":
    get:
      tags:
        - Project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
    put:
      tags:
        - Project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ProjectDto"
          text/json:
            schema:
              "$ref": "#/components/schemas/ProjectDto"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/ProjectDto"
      responses:
        '200':
          description: Success
  "/Project/{id}/members":
    get:
      tags:
        - Project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/MemberResponseDto"
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/MemberResponseDto"
            text/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/MemberResponseDto"
  "/Project/{id}/member/{memberId}/tasks":
    get:
      tags:
        - Project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: memberId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/MemberResponseDto"
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/MemberResponseDto"
            text/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/MemberResponseDto"
  "/Project/{id}/tasks":
    get:
      tags:
        - Project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ProjectTaskResponseDto"
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ProjectTaskResponseDto"
            text/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ProjectTaskResponseDto"
  "/Project/{projectId}/task/{taskId}/member/{memberId}":
    put:
      tags:
        - Project
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: memberId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  "/Project/{id}/member/{memberId}":
    put:
      tags:
        - Project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: memberId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  "/Task/{id}":
    get:
      tags:
        - Task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
    put:
      tags:
        - Task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ProjectTaskDto"
          text/json:
            schema:
              "$ref": "#/components/schemas/ProjectTaskDto"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/ProjectTaskDto"
      responses:
        '200':
          description: Success
  "/Task":
    get:
      tags:
        - Task
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ProjectTaskResponseDto"
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ProjectTaskResponseDto"
            text/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ProjectTaskResponseDto"
    post:
      tags:
        - Task
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ProjectTaskDto"
          text/json:
            schema:
              "$ref": "#/components/schemas/ProjectTaskDto"
          application/*+json:
            schema:
              "$ref": "#/components/schemas/ProjectTaskDto"
      responses:
        '200':
          description: Success
components:
  schemas:
    LoginDto:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      additionalProperties: false
    MemberDto:
      type: object
      properties:
        name:
          type: string
          nullable: true
        surname:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        confirmPassword:
          type: string
          nullable: true
      additionalProperties: false
    MemberResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        surname:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
      additionalProperties: false
    ProjectDto:
      required:
        - deadline
        - description
        - name
      type: object
      properties:
        name:
          maxLength: 25
          type: string
        description:
          type: string
        deadline:
          type: string
          format: date-time
      additionalProperties: false
    ProjectTaskDto:
      required:
        - deadline
        - name
      type: object
      properties:
        name:
          maxLength: 25
          type: string
        description:
          type: string
          nullable: true
        deadline:
          type: string
          format: date-time
        dateOfCreation:
          type: string
          format: date-time
          readOnly: true
        memberId:
          type: integer
          format: int32
          nullable: true
        projectId:
          type: integer
          format: int32
        state:
          "$ref": "#/components/schemas/State"
      additionalProperties: false
    ProjectTaskResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        projectId:
          type: integer
          format: int32
        description:
          type: string
          nullable: true
        deadline:
          type: string
          format: date-time
        dateOfCreation:
          type: string
          format: date-time
          readOnly: true
        memberId:
          type: integer
          format: int32
          nullable: true
        state:
          "$ref": "#/components/schemas/State"
      additionalProperties: false
    State:
      enum:
        - 0
        - 1
        - 2
      type: integer
      format: int32
